build:
  version: "3.1"
cards:
  message: "Welcome to TUS inventory related prod APIs"
  contactDetails:
    name: "John Murphy - Inventory Product Owner"
    email: "john@inventory.ie"
  onCallSupport:
    - (086) 656-8709
    - (087) 342-0956