build:
  version: "2.0"
orders:
  message: "Welcome to orders related local APIs"
  contactDetails:
    name: "Joe Bloggs - Orders Developer"
    email: "joe@orders.ie"
  onCallSupport:
    - (086) 555-1234
    - (086) 523-1345