build:
  version: "2.1"
orders:
  message: "Welcome to orders related prod APIs"
  contactDetails:
    name: "John Bloggs - Prod Support"
    email: "john@orders.ie"
  onCallSupport:
    - (086) 555-1234
    - (087) 523-1345