server:
  port: 8080
spring:
  cloud:
    compatibility-verifier:
      enabled: false # lab 16: disable version check
  application:
    name: "orders" # this is the endpoint
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
   import: "configserver:http://localhost:8071/" # lab 16: config server port 8071
management:
  endpoints:
    web:
      exposure:
        # include: "*" # Lab 19
        include: info, shutdown # lab 22
  endpoint:
    shutdown:
      enabled: true
  info: # indentation!!!!
    env:
      enabled: true
        
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
      
info:
  app:
    name: "orders"
    description: "Microservices Architecture CA2: Guitar Orders Application"
    version: "1.0.0"