build:
  version: "1.2"
orders:
  message: "Welcome to guitar orders related local APIs"
  contactDetails:
    name: "Joe O'Regan - Guitar Orders QA Lead"
    email: "A00258304@student.tus.ie"
  onCallSupport:  
    - (085) 333-5678
    - (089) 333-6789