server:
  port: 8080
spring:
  application:
    name: guitarorders
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
# If profiles needed later
build:
  version: "1.0"
orders:
  message: "Welcome to guitar orders related local APIs"
  contactDetails:
    name: "Joe O'Regan - Orders Developer"
    email: "A00258304@student.tus.ie"
  onCallSupport:  
    - (086) 123-4567
    - (087) 987-6543