build:
  version: "2.1"
inventory:
  message: "Welcome to guitar orders related local APIs"
  contactDetails:
    name: "Joe O'Regan - Guitar Inventory Product Owner"
    email: "A00258304@student.tus.ie"
  onCallSupport:  
    - (085) 222-3456
    - (089) 222-4567