server:
  port: 9090
spring:
  application:
    name: guitarinventory
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_prod.yml"
      - "application_qa.yml"
  profiles:
    active:
      - "prod"
# If profiles needed later
build:
  version: "2.0"
inventory:
  message: "Welcome to guitar inventory related local APIs"
  contactDetails:
    name: "Joe O'Regan - Inventory Lead"
    email: "A00258304@student.tus.ie"
  onCallSupport:  
    - (085) 246-8101
    - (089) 369-1215