server:
  port: 8081
spring:
  application:
    name: guitarinventory
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
# If profiles needed later
build:
  version: "1.0"
inventory:
  message: "Welcome to inventory related local APIs"
  contactDetails:
    name: "Joe O'Regan - Inventory Developer"
    email: "A00258304@student.tus.ie"